# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace '../Demo.xcworkspace'

target 'Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Visuality', '5.4.1'
  pod 'Pixels', '1.4'
  pod 'Degree', '1.0'
  pod 'Hammer', '1.0'
  pod 'Direct', '1.6'
  pod 'Alamofire', '4.7.2'
  pod 'SwiftyJSON', '4.1.0'

end
